<a href="https://colab.research.google.com/github/TheBangis/ArewaDS-Deep-Learning/blob/main/Part_1_Deep_Learning_with_Pytorch/week1/week_1_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/arewadataScience/ArewaDS-Deep-Learning/blob/main/Part_1_Deep_Learning_with_Pytorch/week1/week_1_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Arewa DataScience Academy
### Deep Learning Cohort 1.0
### Name: Babangida Sani
### Email: bsani480@gmail.com

### WEEK 1 Exercises

### Exercises:
Please, see week 1 exercises from [**Learn PyTorch for Deep Learning**: 00. Pytorch Fundamentals](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [1]:
import torch

torch.__version__

'2.1.0+cu121'

#### 1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

#### Read

#### 2. Create a random tensor with shape (7, 7).

In [2]:
tensor = torch.rand(size=(7,7))

tensor, tensor.shape

(tensor([[0.5118, 0.9355, 0.5311, 0.0962, 0.4571, 0.2300, 0.4907],
         [0.4370, 0.4441, 0.3497, 0.5022, 0.9926, 0.8234, 0.0788],
         [0.8420, 0.3890, 0.6711, 0.4683, 0.9719, 0.6504, 0.4154],
         [0.3546, 0.0035, 0.5284, 0.0752, 0.9796, 0.3174, 0.9441],
         [0.0453, 0.1459, 0.3432, 0.8309, 0.5940, 0.0410, 0.8356],
         [0.2436, 0.8844, 0.7758, 0.3069, 0.8545, 0.0220, 0.0116],
         [0.4807, 0.3857, 0.4536, 0.7290, 0.3088, 0.7374, 0.1661]]),
 torch.Size([7, 7]))

#### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [7]:
# create second tensor
second_tensor = torch.rand(size=(1,7))

# multiply first and second tensors
torch.matmul(tensor, second_tensor.T)

tensor([[1.0402],
        [2.4243],
        [1.4873],
        [1.7278],
        [1.4524],
        [1.2654],
        [1.1222]])

#### 4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [11]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# use the tensors created in 2 and 3

# Matrix multiply tensors
a = torch.matmul(tensor, second_tensor.T)
a, a.shape

(tensor([[1.0402],
         [2.4243],
         [1.4873],
         [1.7278],
         [1.4524],
         [1.2654],
         [1.1222]]),
 torch.Size([7, 1]))

##### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [14]:
torch.cuda.manual_seed(1234)

#### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [18]:
torch.cuda.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cpu


(tensor([[0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742]]),
 tensor([[0.4194, 0.5529, 0.9527],
         [0.0362, 0.1852, 0.3734]]))

#### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [19]:
x = torch.matmul(tensor_A, tensor_B.T)
x, x.shape

(tensor([[0.8730, 0.3126],
         [1.4362, 0.4331]]),
 torch.Size([2, 2]))

 #### 8. Find the maximum and minimum values of the output of 7.

In [20]:
max = torch.max(x)
min = torch.min(x)

max, min

(tensor(1.4362), tensor(0.3126))

####  9. Find the maximum and minimum index values of the output of 7.

In [21]:
arg_max = torch.argmax(x)
arg_min = torch.argmin(x)

arg_max, arg_min

(tensor(2), tensor(1))

#### 10.  Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [22]:
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)


tensor_1 = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_2 = tensor_1.squeeze()

print(tensor_1, tensor_1.shape)
print(tensor_2, tensor_2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])


### Additional Exercise